import json
import string
import random
from json import JSONDecodeError
from datetime import datetime

def Register(type,gamers_json_file,sellers_json_file,Email_ID,Username,Password,Contact_Number):
    '''Register Function || Already Given'''
    if type.lower()=='seller':
        f=open(sellers_json_file,'r+')
        d={
            "Email":Email_ID,
            "Username":Username,
            "Password":Password,
            "Contact Number":Contact_Number,
        }
        try:
            content=json.load(f)
            if d not in content and d["Username"] not in str(content):
                content.append(d)
                f.seek(0)
                f.truncate()
                json.dump(content,f)
        except JSONDecodeError:
            l=[]
            l.append(d)
            json.dump(l,f)
        f.close()
        return True
    elif type.lower()=='gamer':
        f=open(gamers_json_file,'r+')
        d={
            "Email":Email_ID,
            "Username":Username,
            "Password":Password,
            "Contact Number":Contact_Number,
            "Wishlist":[],
            "Cart":[],
        }
        try:
            content=json.load(f)
            if d not in content and d["Username"] not in str(content):
                content.append(d)
                f.seek(0)
                f.truncate()
                json.dump(content,f)
        except JSONDecodeError:
            l=[]
            l.append(d)
            json.dump(l,f)
        f.close()

def Login(type,gamers_json_file,sellers_json_file,Username,Password):
    '''Login Functionality || Return True if successfully logged in else False || Already Given'''
    d=0
    if type.lower()=='seller':
        f=open(sellers_json_file,'r+')
    else:
        f=open(gamers_json_file,'r+')
    try:
        content=json.load(f)
    except JSONDecodeError:
        return False
    for i in range(len(content)):
        if content[i]["Username"]==Username and content[i]["Password"]==Password:
            d=1
            break
    f.seek(0)
    f.truncate()
    json.dump(content,f)
    f.close()
    if d==0:
        return False
    return True

def AutoGenerate_ProductID():
    '''Return a autogenerated random product ID || Already Given'''
    product_ID=''.join(random.choices(string.ascii_uppercase+string.digits,k=4))
    return product_ID

def AutoGenerate_OrderID():
    '''Return a autogenerated random product ID || Already Given'''
    Order_ID=''.join(random.choices(string.ascii_uppercase+string.digits,k=3))
    return Order_ID

def days_between(d1, d2):
    '''Calculating the number of days between two dates || Already Given'''
    d1 = datetime.strptime(d1, "%Y-%m-%d")
    d2 = datetime.strptime(d2, "%Y-%m-%d")
    return abs((d2 - d1).days)

def Create_Product(owner,product_json_file,product_ID,product_title,product_type,price_per_day,total_stock_available):
    '''Creating a product || Return True if successfully created else False'''
    '''Write your code below'''

    d = {
        'Seller_name': owner,
        'Product_id': product_ID,
        'Product_Name': product_title,
        'Product_Type': product_type,
        'Price_per_day': price_per_day,
        'total_stock': total_stock_available,
    }
    f = open(product_json_file,'r+')
    try:
        content=json.load(f)
        if d not in content:
            content.append(d)
            f.seek(0)
            f.truncate()
            json.dump(content,f)
        else:
            return False
    except JSONDecodeError:
        l=[]
        l.append(d)
        json.dump(l,f)
    f.close()
    return True


def Fetch_all_Products_created_by_seller(owner,product_json_file):
    '''Get all products created by the seller(owner)'''
    '''Write your code below'''

    seller_products = []
    with open(product_json_file,'r') as f:
        content = json.load(f)
        for product in content:
            if product['Seller_name'] == owner:
                seller_products.append(product)
        return seller_products


def Fetch_all_products(products_json_file):
    '''Get all products created till now || Helper Function || Already Given'''
    All_Products_list=[]
    f=open(products_json_file,'r')
    try:
        content=json.load(f)
        All_Products_list=content
    except JSONDecodeError:
        pass
    return All_Products_list

def Fetch_Product_By_ID(product_json_file,product_ID):
    '''Get product deatils by product ID'''
    '''Write your code below'''
    Product_info = []
    with open(product_json_file,'r') as f:
        try:
            content=json.load(f)
            for product in content:
                if product['Product_id'] == product_ID:
                    Product_info.append(product)
                    return Product_info
        except JSONDecodeError:
            pass
        return Product_info


def Update_Product(Username,product_json_file,product_ID,detail_to_be_updated,new_value):
    '''Updating Product || Return True if successfully updated else False'''
    '''Write your code below'''

    f = open(product_json_file,'r+')
    try:
        content = json.load(f)
        for i in range(len(content)):
            if content[i]['Product_id'] == product_ID and content[i]['Seller_name'] == Username:
                try:
                    nw = content[i][detail_to_be_updated]
                except KeyError:
                    return False
                content[i][detail_to_be_updated] = new_value
                f.seek(0)
                f.truncate()
                json.dump(content,f)
                f.close()
                return True
    except JSONDecodeError:
        f.close()
        return False
        

            
def Add_item_to_wishlist(Username,product_ID,gamers_json_file):
    '''Add Items to wishlist || Return True if added successfully else False'''
    '''Write your code below'''

    f = open(gamers_json_file,'r+')
    try:
        content = json.load(f)
        for i in range(len(content)):
            if content[i]['Username'] == Username:
                if product_ID not in content[i]['Wishlist']:
                    content[i]['Wishlist'].append(product_ID)
                    f.seek(0)
                    f.truncate()
                    json.dump(content,f)
                    f.close()
                    return True
        else:
            f.close()
            return False
    except JSONDecodeError:
        return False


def Remove_item_from_wishlist(Username,product_ID,gamers_json_file):
    '''Remove items from wishlist || Return True if removed successfully else False'''
    '''Write your code below'''

    f = open(gamers_json_file,'r+')
    try:
        content = json.load(f)
        for i in range(len(content)):
            if content[i]['Username'] == Username:
                if product_ID in content[i]['Wishlist']:
                    content[i]['Wishlist'].remove(product_ID)
                    f.seek(0)
                    f.truncate
                    json.dump(content,f)
                    f.close()
                    return True
        else:
            f.close()
            return False
    except JSONDecodeError:
        return False

    

def Add_item_to_cart(Username,product_ID,Quantity,gamers_json_file,booking_start_date,booking_end_date,products_json_file):
    '''Add item to the cart || Check whether the quantity mentioned is available || Return True if added successfully else False'''
    '''Add the Product ID, Quantity, Price, Booking Start Date, Booking End Date in the cart as list of dictionaries'''
    '''Write your code below'''

    with open(products_json_file,'r') as f1, open(gamers_json_file,'r+') as f2:
        try:
            content1 = json.load(f1)
            content2 = json.load(f2)
            for product in content1:
                if product['Product_id'] == product_ID and product['total_stock'] >= Quantity:
                    d={
                        'Product_id':product_ID,
                        'Quantity':Quantity,
                        'Price':product['Price_per_day'],
                        'Booking Start Date':booking_start_date,
                        'Booking End Date':booking_end_date
                    }

                    for i in range(len(content2)):
                        if content2[i]['Username'] == Username:
                            content2[i]['Cart'].append(d)
                            f2.seek(0)
                            f2.truncate()
                            json.dump(content2,f2)
                            return True
                    else:
                        return False            
            else:
                return False
        except JSONDecodeError:
            return False


def Remove_item_from_cart(Username,product_ID,gamers_json_file):
    '''Remove items from the cart || Return True if removed successfully else False'''
    '''Write your code below'''

    with open(gamers_json_file,'r+') as f:
        try:
            content = json.load(f)
            for i in range(len(content)):
                if content[i]['Username'] == Username:
                    for product in content[i]['Cart']:
                        if product['Product_id'] == product_ID:
                            content[i]['Cart'].remove(product)
                            f.seek(0)
                            f.truncate()
                            json.dump(content,f)
                            return True
                    else:
                        return False
            else:
                return False
        except JSONDecodeError:
            return False



def View_Cart(Username,gamers_json_file):
    '''Return the current cart of the user'''
    '''Write your code below'''

    f = open(gamers_json_file,'r')
    try:
        content = json.load(f)
        for user in content:
            if user['Username'] == Username:
                return user['Cart']
    except JSONDecodeError:
        f.seek(0)
        f.truncate()
        json.dump(content,f)
        f.close()


def Place_order(Username,gamers_json_file,Order_Id,orders_json_file,products_json_file):
    '''Place order || Return True is order placed successfully else False || Decrease the quantity of the product orderd if successfull'''
    '''Write your code below'''

    g = open(gamers_json_file,'r+')
    o = open(orders_json_file,'r+')
    p = open(products_json_file,'r+')
    try:
        gamecon = json.load(g)
        ordercon = json.load(o)
        procon = json.load(p)
        for i in range(len(gamecon)):
            if gamecon[i]['Username'] == Username:
                order = {
                    'Order ID': Order_Id,
                    'Ordered by': Username,
                    'Items': gamecon[i]['Cart']
                }
                money = 0
                for j in gamecon[i]['Cart']:
                    bsd = datetime.strptime(j['Booking Start Date'],'%Y-%m-%d')
                    bed = datetime.strptime(j['Booking End Date'],'%Y-%m-%d')
                    days = (bed-bsd).days
                    money = money + (days * j['Price'] * j['Quantity'])
                    for k in range(len(procon)):
                        if procon[k]['Product_id'] == j['Product_id']:
                            procon[k]['total_stock'] -= j['Quantity']
                order['Total Cost'] = money
                ordercon.append(order)
                g.seek(0)
                g.truncate()
                json.dump(gamecon,g)
                g.close()
                o.seek(0)
                o.truncate()
                json.dump(ordercon,o)
                o.close()
                p.seek(0)
                p.truncate
                json.dump(procon,p)
                p.close()
                return True
        return False
    except JSONDecodeError:
        return False


def View_User_Details(gamers_json_file,Username):
    '''Return a list with all gamer details based on the username || return an empty list if username not found'''
    '''Write your code below'''

    f = open(gamers_json_file,'r+')
    userdetails = []
    try:
        content = json.load(f)
        for i in range(len(content)):
            if content[i]['Username'] == Username:
                userdetails.append(content[i])
                return userdetails
    except JSONDecodeError:
        pass
    f.close()
    return userdetails   

def Update_User(gamers_json_file,Username,detail_to_be_updated,updated_detail):
    '''Update the detail_to_be_updated of the user to updated_detail || Return True if successful else False'''
    '''Write your code below'''

    f = open(gamers_json_file,'r+')
    try:
        content = json.load(f)
        for i in range(len(content)):
            if content[i]['Username'] == Username:
                try:
                    a = content[i][detail_to_be_updated]
                except KeyError:
                    return False
                content[i][detail_to_be_updated] = updated_detail
                f.seek(0)
                f.truncate()
                json.dump(content,f)
                f.close()
                return True
        else:
            return False
    except JSONDecodeError:
        f.close()
        return False
            

def Fetch_all_orders(orders_json_file,Username):
    '''Fetch all previous orders for the user and return them as a list'''
    '''Write your code below'''

    with open(orders_json_file,'r+')as f:
        ord = []
        try:
            content = json.load(f)
            for i in range(len(content)):
                if content[i]['Ordered by'] == Username:
                    ord.append(content[i])
        except JSONDecodeError:
            pass
        return ord
